user:
  maximum_of_name: 255
  maximum_of_email: 255
  maximum_of_phone: 20
  minimum_of_password: 6

comment:
  maximum_of_content: 255

post:
  maximum_of_title: 255
  maximum_of_content: 255
  maximum_of_size_picture: 5
